### ISSUE TITLE
SceneViewer doesnot work in my Android Device but WebXR works

### ISSUE THREAD

**Issue by monkeyMax-SVG** [google/model-viewer#2264]
### Description

Hello, I have some troubles in AR experience with scene-viewer. 2~3 weeks ago, I have built project with model-viewer, and AR worked perfectly with scene-viewer in android devices chrome version.
After some days, today, I tried to open the my project in mobile browser but AR experience is not working.
when the mobile detects the ground, the models 

are not showed in the 3D scene, I can only see the camera

So I tried to test the examples from model-viewer official site but it had same problems.
Webxr works but no scene viewer

I cannot see any errors messages checking in chrome://inspect/#devices

#### Live Demo
https://modelviewer.dev/examples/augmentedreality/#sceneViewer
https://monkeymax-svg.github.io/dev-modelviewer/

### Version

- model-viewer: v1.6.0

### Browser Affected

- [x] Chrome, version: 89.0.4389.105 (March 22  2021 update)

### OS

- Samsung note 8 with Android 9.0
- Pocophone Android 10
These devices are ARcore compatible and examples worked on these devices perfectly some weeks ago

### AR

- WebXR works well
- SceneViewer has issues what I see.
-

**Comment by canberka** [comment]
we have an problem too.. https://modelviewer.dev/examples/augmentedreality/index.html#sceneViewer this example is not working and also our projects are not working.... but when i try to open google search default animal Ar like Tiger, cat and dog etc... its working .... i think they are scene viewer too .... samsung s9 i use ...

**Comment by imartini** [comment]
Same here, our projects in scene viewer it's not working now, and the model viewer examples doesn't work, only the projects with webxr and we can't use the webxr beccause doesn't have the screenshot button.

**Comment by sercandemirtas** [comment]
Since 3 or 4 days we are having same problem (when the mobile detects the ground, the models are not showed in the 3D scene, I can only see the camera ) on some Android devices via "Scene Viewer"

**Comment by AndresSalomon1990** [comment]
Ok, I will follow this issue. The same is happening to me. I'm using the attribute like this: 

`ar-modes="scene-viewer webxr quick-look" `

in order to force to use the scene-viewer first because it allow the user to take snapshots and record videos. But in my phone (Nokia 7.1 - Android 10 - supports Google Play Services for AR), when you enter the AR, it shows the loader and all the buttons but not the 3D model; so you see only through the camera. But it works perfectly with the webxr (this one doesn't have the option to take snapshots/record videos). Don't know what is happening in iOS. 

Hope someone can help here!

**Comment by sercandemirtas** [comment]
@AndresSalomon1990 on iOS (Quick-Look) everything is normal. It looks like the problem is just on Scene-Viewer.

**Comment by AndresSalomon1990** [comment]
Thanks @sercandemirtas, good to know! Hoping this could be fixed.

**Comment by AndresSalomon1990** [comment]
An update.

I was trying with my teammates and they can use the RA perfectly. They have a Samsung A31 and a Motorla One Fusion. Just to keep in mind that maybe the problem is in some devices or in a configuration of the device.

Another thing, I'm using Netlify with a Github repo to serve it. Don't know if Netlify has some troubles with AR.

**Comment by elalish** [comment]
@tpsiaki @AdrianAtGoogle Looks like a significant recent regression in Scene Viewer?

**Comment by tpsiaki** [comment]
Yes this looks like a regression in the Scene Viewer build that shipped last week. We have this fixed internally, and the next release of the Google app will include it (should be available in the next few days).

**Comment by canberka** [comment]
> An update.
> 
> I was trying with my teammates and they can use the RA perfectly. They have a Samsung A31 and a Motorla One Fusion. Just to keep in mind that maybe the problem is in some devices or in a configuration of the device.
> 
> Another thing, I'm using Netlify with a Github repo to serve it. Don't know if Netlify has some troubles with AR.

yes we tried.. it works on some android devices but not on me...

**Comment by AndresSalomon1990** [comment]
Hi all! Hope you are doing good. Is there any update on this topic? Thank you :)

**Comment by tpsiaki** [comment]
@AndresSalomon1990 which version of the Google app is installed on the device where this is reproing? We believe this is fixed since 12.13 which was pushed on Monday.

**Comment by AndresSalomon1990** [comment]
Hi @tpsiaki ! I have the **12.14.7.23.arm64** . Is that the version I should look up? My problem is still the same, when enter the RA with Scene Viewer (not WebXR), I see the loader and buttons, but the model never appears. With WebXR works fine. Could be something with my phone (Nokia 7.1)?

**Comment by tpsiaki** [comment]
Thanks. I think I have a repro now. I believe it involves having AR tracking find a plane before the model is fully loaded. If you cover the camera for a while before placing the object does it work for you? If so then I think I'm reproing the same issue.

We'll work on a fix.

**Comment by canberka** [comment]
still same issue...

 here is a video .. WebXR works well... Samsung s9 android 12

https://user-images.githubusercontent.com/36857390/115099202-04f63d80-9f3d-11eb-93e0-e07c481b11d8.mp4

**Comment by canberka** [comment]
> Thanks. I think I have a repro now. I believe it involves having AR tracking find a plane before the model is fully loaded. If you cover the camera for a while before placing the object does it work for you? If so then I think I'm reproing the same issue.
> 
> We'll work on a fix.

yes it works when i cover the camera for a while...

**Comment by AndresSalomon1990** [comment]
All the same as @canberka . The video reflect exactly what is happening to me. And also, if I cover the camer, it shows the model! Hope you can fix this @tpsiaki :D may the force be with you

**Comment by andrewdeutsch** [comment]
Hi @tpsiaki, has there been any luck sorting out this issue? Thanks in advance.

**Comment by david-rhodes** [comment]
I'm also experiencing this issue. Google App 12.15.9.23.arm64 (April 23, 2021), Pixel 3a XL.

**Comment by imartini** [comment]
Seems its working now in my case, scene viewer works with Chrome 90.0.4430.91  (updated in 26 April) and Arcore 1.24.210950423 (update April 15).

**Comment by AndresSalomon1990** [comment]
For me, still the same :(

**Comment by AdrianAtGoogle** [comment]
The next update of aGSA has a fix (the release from 4/23 does not) - apologies.

**Comment by david-rhodes** [comment]
Thank you for the clarity @AdrianAtGoogle!

**Comment by imartini** [comment]
Sorry, for some reason It worked during a days and today started not working ... we will wait for the fix.

**Comment by AndresSalomon1990** [comment]
Hi all! I just test it again and now is working in my device! 😄 Sometimes it takes a bit to load but works (snapshot, record video, drag and drop, scale). Also, it shows a tooltip that says: _"Integración de objeto desactivada" (I have it in spanish - in english could be "Object integration disabled");_ and then, when it places the model: _"Integración de objeto activada" ("Object integration enabled" I think)._

Is it working for anyone else?

**Comment by pfortes** [comment]
I was having the same problem and noticed the scene-viewer had a pupup dialog asking for permissions before it crashes.
![WhatsApp Image 2021-05-21 at 4 45 57 PM](https://user-images.githubusercontent.com/782464/119201459-96812f80-ba54-11eb-8066-de022a6b8316.jpeg)

What i had to do to get rid of it is open the oficial AR scene viewer example from https://modelviewer.dev/examples/augmentedreality/#sceneViewer and load it in scene viewer, for some reason this does not crash and lets you accept the permissions.
After that all my AR projects started working perfectly.

Hope this helps 🍔

**Comment by elalish** [comment]
Looks like this is fixed.
